name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build-binaries:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: linux-aarch64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: macos-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows-x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install build dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install cross compilation toolchain (Linux ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
            ${{ runner.os }}-cargo-

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/oidc-cli release/oidc-cli-${{ matrix.name }}
          chmod +x release/oidc-cli-${{ matrix.name }}

      - name: Prepare binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir release
          cp target/${{ matrix.target }}/release/oidc-cli.exe release/oidc-cli-${{ matrix.name }}.exe

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.name }}
          path: release/oidc-cli-*

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-binaries]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all binary artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: binary-*
          merge-multiple: true
          path: release

      - name: Generate release notes
        id: release_notes
        run: |
          echo "## OIDC CLI Release ${{ github.ref_name }}" >> release_notes.md
          echo "" >> release_notes.md
          echo "A command-line tool for OIDC authentication with AWS credential management." >> release_notes.md
          echo "" >> release_notes.md
          echo "### Installation" >> release_notes.md
          echo "" >> release_notes.md
          echo "Download the appropriate binary for your platform from the assets below:" >> release_notes.md
          echo "" >> release_notes.md
          echo "- **Linux x86_64**: \`oidc-cli-linux-x86_64\`" >> release_notes.md
          echo "- **Linux ARM64**: \`oidc-cli-linux-aarch64\`" >> release_notes.md
          echo "- **macOS x86_64**: \`oidc-cli-macos-x86_64\`" >> release_notes.md
          echo "- **macOS ARM64** (Apple Silicon): \`oidc-cli-macos-aarch64\`" >> release_notes.md
          echo "- **Windows x86_64**: \`oidc-cli-windows-x86_64.exe\`" >> release_notes.md
          echo "" >> release_notes.md
          echo "### Usage" >> release_notes.md
          echo "" >> release_notes.md
          echo "After downloading, make the binary executable (on Unix systems) and run:" >> release_notes.md
          echo "\`\`\`bash" >> release_notes.md
          echo "chmod +x oidc-cli-*" >> release_notes.md
          echo "./oidc-cli-* --help" >> release_notes.md
          echo "\`\`\`" >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}